### PR TITLE
fix: virutal manager can't probe correct vm controller path

### LINKED ISSUE #109: /tmp/cuda-control/src/loader.c:856 can't find library libcuda.so.
###  My experiment environment
**k8s=v1.16.11, os=ubuntu18.04, test-image=menghe.tencentcloudcr.com/public/tensorflow-gputest:0.2**
### My experiment

1. I want 5 pod which shares the only one GPU on my node. 
2. So I applied a deployment whose replicas is 5. The yaml file is like the picture below shows.
image

3. All the pods run.
4. But when I started a training task in one pod, I got error: "/tmp/cuda-control/src/loader.c:856 can't find library libcuda.so.".  

**The reason is that vcuda.so failed to open 'config_path' and 'goto DONE' which caused driver_version always be null. Besides, I found that the config in /etc/vcuda is wrong. It seems that the container mounted a wrong hostPath. Runned "docker inspect" and I got the message like the photo below which proved my guess. But I found that in allocator the reponse of allocate request is right. Is it a bug in gpu-manager or kubelet? Please help.**

image

### PR DESCRIPTION
**Pull request by mYmNeo**
fix #109 

Signed-off-by: thomassong <thomassong2012@gmail.com>

### CODE REVIEW

File: pkg/services/virtual-manager/manager.go [hunk 1]
```diff
@@ -367,7 +361,17 @@ func (vm *VirtualManager) process() {
 
 func (vm *VirtualManager) registerVDeviceWithContainerId(podUID, contID string) (*vcudaapi.VDeviceResponse, error) {
 	klog.V(2).Infof("UID: %s, cont: %s want to registration", podUID, contID)
-	baseDir := filepath.Clean(filepath.Join(vm.cfg.VirtualManagerPath, podUID))
+
+	resp := vm.responseManager.GetResp(podUID, contID)
```
Comment (fighterhit) [inline pkg/services/virtual-manager/manager.go:365]: The `responseManager` uses the `container name` as the key, so I think it will not be found when the `container id` is passed in.
